# Python Refresh
Python fundamentals revisited: data structures, comprehensions, functions.

In [2]:
# we can specify a value for sep to put some special string in between our printed arguments:
print(1, 2, 3, sep=' < ')

1 < 2 < 3


In [3]:
# 
def greet(who="Colin"):
    print("Hello,", who)
    
greet()
greet(who="Kaggle")
# (In this case, we don't need to specify the name of the argument, because it's unambiguous.)
greet("world")

Hello, Colin
Hello, Kaggle
Hello, world


# NumPy
NumPy library contains multidimensional array data structures.

In [4]:
import numpy as np

## Creating an array
Two- and higher-dimensional arrays can be initialized from nested Python sequences


In [5]:
# Put a square bracket outside the array. 

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array attributes

### .ndim
- The number of dimensions of an array is contained in the ndim attribute.

### .size
- The fixed, total number of elements in array is contained in the size attribute

In [6]:
print(a)
print("Number of dimensions:", a.ndim)
print("Shape:", a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions: 2
Shape: (3, 3)


## Creating a basic array
### .zeros()
- create an array filled with 0’s
### .ones()
- array filled with 1’s
### .empty()
- creates an array whose initial content is random and depends on the state of the memory
### .arrange()
- create an array with a range of elements from 0 to x, or
- an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
### .linspace
- create an array with values that are spaced linearly in a specified interval

### np.empty vs np.zeros
The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

### np.arrange vs np.linspace
- np.arange(start, stop, step) — you specify the step size, and it generates values until it hits (but doesn't include) stop
- np.linspace(start, stop, num) — you specify the number of elements, and NumPy figures out the step size to fit num evenly-spaced points between start and stop (inclusive by default).
- Rule of thumb to internalize: ask yourself "do I care how many points I get, or do I care about the size of each step?" — count-driven → linspace; step-driven → arange.

In [7]:
# Create an empty array with 2 elements
a = np.empty(2)
print("np.empty(2): An empty array with 2 elements: \n", a) # may vary

# To create an array with 3 rows, 2 elements using .ones and .zeros, we can specify the shape as a tuple:
a = np.ones((3, 2))
print("np.ones((3, 2)): An array of ones with 3 rows and 2 columns:\n", a) 
a = np.zeros((3, 2))
print("np.zeros((3, 2)): An array of zeros with 3 rows and 2 columns:\n", a)

# Using arrange for its two separate arguments, start and stop, we can create an array of evenly spaced values:
a = np.arange(3, 7)
print("np.arange(3, 7): An array of evenly spaced values from 3 to 7:\n", a)
a = np.arange(3, 7, 2)
print("np.arange(3, 7, 2): An array of evenly spaced values from 3 to 7 with a step of 2:\n", a)

# Using linspace, we can create an array of evenly spaced values over a specified interval:
a = np.linspace(3, 7, 2)
print("np.linspace(3, 7, 2): An array of 5 evenly spaced values from 3 to 7:\n", a)

np.empty(2): An empty array with 2 elements: 
 [0. 0.]
np.ones((3, 2)): An array of ones with 3 rows and 2 columns:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.zeros((3, 2)): An array of zeros with 3 rows and 2 columns:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
np.arange(3, 7): An array of evenly spaced values from 3 to 7:
 [3 4 5 6]
np.arange(3, 7, 2): An array of evenly spaced values from 3 to 7 with a step of 2:
 [3 5]
np.linspace(3, 7, 2): An array of 5 evenly spaced values from 3 to 7:
 [3. 7.]


## Adding, removing, and sorting elements

### np.sort(a, axis=-1, kind=None, order=None, *, stable=None, descending=<no value>)
Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

a: array_like

    Array to be sorted.
axis: int or None, optional

    Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

**Ignore for now: kind, order, stable. These are for edge cases (structured arrays, guaranteeing tie-order) you won't hit in tabular EDA work. Default behavior is fine.**

### np.argsort(a, axis=-1, kind=None, order=None)
Returns the indices that would sort the array, not the sorted values.
axis — same logic as sort. Default -1 sorts indices along the last axis (each row independently for 2D). axis=0 would give you, for each column, the row-order that sorts that column.
### np.concatenate()
To concatenate two arrays.

In [8]:
a = np.array([[3, 1, 2],
              [9, 7, 8]])

np.sort(a, axis=-1)   # sorts each row
# [[1, 2, 3],
#  [7, 8, 9]]

np.sort(a, axis=0)    # sorts each column
# [[3, 1, 2],
#  [9, 7, 8]]   -> becomes column-wise sorted

np.sort(a, axis=None) # flattens everything first, one sorted 1D array

array([1, 2, 3, 7, 8, 9])

In [9]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Array a:\n", a)
print("Array b:\n", b)

np.concatenate((a, b), axis=0)
# [[1, 2],
#  [3, 4],
#  [5, 6],
#  [7, 8]]   -> more rows added
print("Concatenating along axis 0:\n", np.concatenate((a, b), axis=0))

np.concatenate((a, b), axis=1)
# [[1, 2, 5, 6],
#  [3, 4, 7, 8]]  -> more columns added
print("Concatenating along axis 1:\n", np.concatenate((a, b), axis=1))

Array a:
 [[1 2]
 [3 4]]
Array b:
 [[5 6]
 [7 8]]
Concatenating along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenating along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


# Pandas
The most popular Python library for data analysis.

In [10]:
import pandas as pd

## DataFrame
A table. It contains an array of individual entries, each of which has a certain value, Each entry corresponds to a row and a column.

In [11]:
a = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
print("DataFrame a:\n", a, ".\nConstructed from a list of lists (row-oriented). Each inner list is one row; columns= labels them separately. This is how you build a DataFrame when your data naturally comes as records — one row per observation, many columns of mixed types.")

b = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
print("DataFrame b:\n", b, "\nConstructed from a dict of lists (column-oriented). Each key becomes a column, and the dict values are that column's data down all rows. This suits data that's already aggregated by category — e.g. a small summary table.")


DataFrame a:
    A  B
0  1  2
1  3  4 .
Constructed from a list of lists (row-oriented). Each inner list is one row; columns= labels them separately. This is how you build a DataFrame when your data naturally comes as records — one row per observation, many columns of mixed types.
DataFrame b:
    Yes   No
0   50  131
1   21    2 
Constructed from a dict of lists (column-oriented). Each key becomes a column, and the dict values are that column's data down all rows. This suits data that's already aggregated by category — e.g. a small summary table.


## DataFrame with Index
The dictionary-list constructor assigns values to the column labels, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the row labels. Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.

The list of row labels used in a DataFrame is known as an Index. We can assign values to it by using an index parameter in our constructor

In [12]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

print("DataFrame constructed from a dict of dicts:\n", pd.DataFrame({'Bob': {'Product A': 'I liked it.', 'Product B': 'It was awful.'},
              'Sue': {'Product A': 'Pretty good.', 'Product B': 'Bland.'}}), "\n\nThis is a dict of dicts. The outer dict keys are the column labels, and the inner dict keys are the row labels. This is a convenient way to construct a DataFrame when you have a small amount of data that you want to enter manually, and you want to specify both the row and column labels.")

pd.DataFrame([[1,2,3], [4,5,6]], 
             index=['cobra', 'viper'], 
             columns=['max_speed', 'shield', 'armor'])

print("\nDataFrame constructed from a list of lists with specified index and columns:\n", pd.DataFrame([[1,2,3], [4,5,6]], index=['cobra', 'viper'], columns=['max_speed', 'shield', 'armor']), "\n\nThis is a list of lists. The outer list contains the rows, and the inner lists contain the values for each column. The index parameter specifies the row labels, and the columns parameter specifies the column labels. This is a convenient way to construct a DataFrame when you have a small amount of data that you want to enter manually, and you want to specify both the row and column labels.")

DataFrame constructed from a dict of dicts:
                      Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland. 

This is a dict of dicts. The outer dict keys are the column labels, and the inner dict keys are the row labels. This is a convenient way to construct a DataFrame when you have a small amount of data that you want to enter manually, and you want to specify both the row and column labels.

DataFrame constructed from a list of lists with specified index and columns:
        max_speed  shield  armor
cobra          1       2      3
viper          4       5      6 

This is a list of lists. The outer list contains the rows, and the inner lists contain the values for each column. The index parameter specifies the row labels, and the columns parameter specifies the column labels. This is a convenient way to construct a DataFrame when you have a small amount of data that you want to enter manually, and you want to specify both the ro

## Series
- A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list.
- A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an index parameter.
- However, a Series does not have a column name

In [13]:
a = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'])
print("Series a:\n", a, "\n\nThis is a Series. The first argument is the data, the second argument is the index (row labels), and the name parameter specifies the name of the Series. This is a convenient way to construct a Series when you have a small amount of data that you want to enter manually, and you want to specify both the index and the name of the Series.")

Series a:
 2015 Sales    30
2016 Sales    35
2017 Sales    40
dtype: int64 

This is a Series. The first argument is the data, the second argument is the index (row labels), and the name parameter specifies the name of the Series. This is a convenient way to construct a Series when you have a small amount of data that you want to enter manually, and you want to specify both the index and the name of the Series.


## Reading Data Files
pd.read_csv() function to read the data into a DataFrame

In [ ]:
resale_prices = pd.read_csv('resale_prices.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'ds-sprint-july/week1_python_pandas_viz/01_python_refresh.ipynb'